export const properties = [
    {
        id: 1,
        image: 'card1.webp',
        listing: 'Apartment/Rent',
        price: '$2000',
        agent: 'John Doe',
        avatar: 'av1.jpg',
    },
    {
        id: 2,
        image: 'card2.webp',
        listing: 'House/Sell',
        price: '$500000',
        agent: 'Jane Smith',
        avatar: 'av2.jpg',
    },
    {
        id: 3,
        image: 'card3.webp',
        listing: 'Studio/Sell',
        price: '$50000',
        agent: 'Jane Smith',
        avatar: 'img1.webp',
    },
    {
        id: 4,
        image: 'card4.jpg',
        listing: 'Apartment/Rent',
        price: '$35,600',
        agent: 'Young Filz',
        avatar: 'av3.jpg',
    },
    {
        id: 5,
        image: 'card5.jpg',
        listing: 'House/Sell',
        price: '$19,000',
        agent: 'Moses Aloyr',
        avatar: 'av4.jpg',
    },
    {
        id: 6,
        image: 'card6.jpg',
        listing: 'Studio/Sell',
        price: '$980,000',
        agent: 'Daisy Smith',
        avatar: 'av5.jpg',
    },
];